version: '3.8'

services:
  jobjet-db:
    image: mysql:8.0
    container_name: jobjet-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456  
      MYSQL_DATABASE: jobjet_db
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    container_name: jobjet-backend
    restart: on-failure
    build:
      context: ./backend-springboot
    ports:
      - "8080:8080"
    depends_on:
      - jobjet-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://jobjet-db:3306/jobjet_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

volumes:
  mysql_data: